name: aaa
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  rl:
    path: rust_builder
  flutter_rust_bridge: 2.11.1

  build_runner: ^2.7.0
  mobx_codegen: ^2.7.2

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - misc/icon.png
